### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by neodave** [smartvipere75/bottombar-swiftui#2]
Hello, wonderful work. I don't believe you have chosen a license for this code. If you choose to open source it I suggest using the MIT license. We are interested in integrating some of this, but need your license to be defined.

**Comment by smartvipere75** [comment]
@neodave Appreciate your interest, added MIT license now. Feel free to use it, just don't forget to mention me wherever you'll use it. Stay safe from COVID.

**Comment by neodave** [comment]
Thank you! We ended up rolling our own, but glad this is available for the community. We have some open source packages at the [neone account](https://github.com/neone) here, but none are SwiftUI. Once we get our new frameworks done we will probably open source them too. Thanks, and stay safe too.
