### ISSUE TITLE
Does this still work？

### ISSUE THREAD

**Issue by L1cardo** [smartvipere75/bottombar-swiftui#3]
I tested on my device , did not work, I don't know why.

the tab item did not switch 

![iShot2020-05-07下午08 17 18](https://user-images.githubusercontent.com/33802186/81293652-3bc2a300-90a0-11ea-84cb-9104f959dcd3.gif)

xcode version: 11.4.1 (11E503a)

**Comment by AnarchoSystems** [comment]
Had the same problem. See my pull request.

> I tested on my device , did not work, I don't know why.
> 
> the tab item did not switch
> 
> ![iShot2020-05-07下午08 17 18](https://user-images.githubusercontent.com/33802186/81293652-3bc2a300-90a0-11ea-84cb-9104f959dcd3.gif)
> 
> xcode version: 11.4.1 (11E503a)

**Comment by smartvipere75** [comment]
@L1cardo Due to new iOS, SwiftUI logic changed and BottomBar stopped working. However thanks to @AnarchoSystems for updating it.
