### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by AnarchoSystems** [smartvipere75/bottombar-swiftui#6]
Apparently, this small toy/tool got a little bit of attention from the community. Could the owner of the repo please clarify under which conditions pull requests that add or modify features (i.e. not just bug fixes) will be accepted/considered?

**Comment by smartvipere75** [comment]
@AnarchoSystems Hello, you can make pull requests to add or modify features. Every pull request will be code reviewed by me, and if it's appropriate than I'll merge it. Feel free to ask any questions. Stay safe.
